unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ==================================
# THEME
# ==================================
# Colors
white="#e3e5e5"
lavender="#a3aed2"
blue="#769ff0"
dark_blue="#394260"
deep_slate="#212736"
darkest="#1d2230"
grey="#585b70"
black="#090c0c"
# Interactive Selection 
set -g mode-style "fg=${white},bg=${dark_blue}"

# Base Status Bar Style
set -g status-position top
set -g status-style "fg=${white},bg=default"

# # Left Status (Session Tracking)
# set -g status-left-length 100
# set -g status-left "#[fg=${primary_blue},bold] #S #[fg=${text_white},nobold] | "
#
# # Right Status (CPU/RAM Usage)
# set -g status-right "#[fg=${primary_blue}]#(~/.config/tmux_stats.sh) #[fg=${text_white}]"
#
# # Window Tabs
# set -g window-status-current-format "#[fg=${primary_blue},bold]  #[underscore]#I:#W"
# set -g window-status-format " #I:#W"
# set -g window-status-style "fg=${text_white}"
#
# set -g mode-style "fg=${text_white},bg=${muted_grey}"

# Left Status (Session Tracking)
set -g status-left-length 100
set -g status-left "#[fg=${black},bg=${lavender},bold]  #S #[fg=${lavender},bg=${dark_blue}]"

# Right Status (CPU/RAM Usage)
set -g status-right-length 100
set -g status-right "#[fg=${white}]#(~/.config/tmux_stats.sh) "

# Window Tabs 
# # Inactive Tab
set -g window-status-style "fg=${lavender},bg=${dark_blue}"
set -g window-status-format " #I:#W "

# # Active Tab
set -g window-status-current-format "#[fg=${dark_blue},bg=${blue}]#[fg=${darkest},bold] #I:#W #[fg=${blue},bg=${dark_blue}]"

# Window Borders
set -g pane-border-style "fg=${dark_blue}"
set -g pane-active-border-style "fg=${blue}"

